name: nightly-build

on:
  schedule:
    - cron:  '10 3 * * *'    # täglich 03:10 UTC
  workflow_dispatch:

permissions:           #  ← NEU
  contents: write      #  für Push auf gh-pages
  pages:   write       #  optional, falls Du Pages-Deployment v2 nutzt
  id-token: write      #  optional, falls Du OIDC für Pages verwendest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests psycopg2-binary python-dateutil

      - name: Run build.py
        env:
          PG_URI: ${{ secrets.PG_URI }}
        run: python build.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          # jetzt darf dieser Token die gh-pages-Branch beschreiben
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site
